title: Zoe Catherine Rudnick
description: This is a portfolio of my projects.
theme: jekyll-theme-minima

nav:
  - title: Home
    url: /
  - title: Projects
    url: /projects
  - title: About
    url: /about
